// File generated by FlutterFire CLI / synced from android/app/google-services.json.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIYiRbZcVVhlTQbI6KgFS-lUl3jOyfEJk',
    appId: '1:140652528868:web:f293011bc617d075b458f1',
    messagingSenderId: '140652528868',
    projectId: 'mnd-masterndelivery',
    authDomain: 'mnd-masterndelivery.firebaseapp.com',
    storageBucket: 'mnd-masterndelivery.firebasestorage.app',
    measurementId: 'G-3PMC2Y9QQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9jKCRCr7PKqskhk7SNBI12rogIhcHlp4',
    appId: '1:140652528868:android:ed007cc4edf55f7fb458f1',
    messagingSenderId: '140652528868',
    projectId: 'mnd-masterndelivery',
    storageBucket: 'mnd-masterndelivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_lkvzXLMmEk1SouuQsmYEaNsjGshNO7E',
    appId: '1:140652528868:ios:2acab2e340ea8099b458f1',
    messagingSenderId: '140652528868',
    projectId: 'mnd-masterndelivery',
    storageBucket: 'mnd-masterndelivery.firebasestorage.app',
    iosBundleId: 'com.example.mndDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_lkvzXLMmEk1SouuQsmYEaNsjGshNO7E',
    appId: '1:140652528868:ios:2acab2e340ea8099b458f1',
    messagingSenderId: '140652528868',
    projectId: 'mnd-masterndelivery',
    storageBucket: 'mnd-masterndelivery.firebasestorage.app',
    iosBundleId: 'com.example.mndDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIYiRbZcVVhlTQbI6KgFS-lUl3jOyfEJk',
    appId: '1:140652528868:web:4f1f90bb557ddde8b458f1',
    messagingSenderId: '140652528868',
    projectId: 'mnd-masterndelivery',
    authDomain: 'mnd-masterndelivery.firebaseapp.com',
    storageBucket: 'mnd-masterndelivery.firebasestorage.app',
    measurementId: 'G-FDGESSXFFM',
  );
}
