// File generated by FlutterFire CLI (MND Firebase project).
// Android: com.mnd.mnd_shop. iOS/macOS bundle: com.mnd.mndShop.
// Re-run `flutterfire configure` after registering the shop iOS app in Firebase.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux — '
          'run FlutterFire CLI with Linux support if needed.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIYiRbZcVVhlTQbI6KgFS-lUl3jOyfEJk',
    appId: '1:140652528868:web:f293011bc617d075b458f1',
    messagingSenderId: '140652528868',
    projectId: 'mnd-masterndelivery',
    authDomain: 'mnd-masterndelivery.firebaseapp.com',
    storageBucket: 'mnd-masterndelivery.firebasestorage.app',
    measurementId: 'G-3PMC2Y9QQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9jKCRCr7PKqskhk7SNBI12rogIhcHlp4',
    appId: '1:140652528868:android:bf295389ca227583b458f1',
    messagingSenderId: '140652528868',
    projectId: 'mnd-masterndelivery',
    storageBucket: 'mnd-masterndelivery.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_lkvzXLMmEk1SouuQsmYEaNsjGshNO7E',
    appId: '1:140652528868:ios:b37016b4c7df3e0db458f1',
    messagingSenderId: '140652528868',
    projectId: 'mnd-masterndelivery',
    storageBucket: 'mnd-masterndelivery.firebasestorage.app',
    androidClientId: '140652528868-ejb6m15gnljqj13ohsedtu7ssr8vtrdm.apps.googleusercontent.com',
    iosClientId: '140652528868-fe1j21duqml6kj5npjq7e39sueaj2hus.apps.googleusercontent.com',
    iosBundleId: 'com.mnd.mndShop',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_lkvzXLMmEk1SouuQsmYEaNsjGshNO7E',
    appId: '1:140652528868:ios:b37016b4c7df3e0db458f1',
    messagingSenderId: '140652528868',
    projectId: 'mnd-masterndelivery',
    storageBucket: 'mnd-masterndelivery.firebasestorage.app',
    iosBundleId: 'com.mnd.mndShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIYiRbZcVVhlTQbI6KgFS-lUl3jOyfEJk',
    appId: '1:140652528868:web:4f1f90bb557ddde8b458f1',
    messagingSenderId: '140652528868',
    projectId: 'mnd-masterndelivery',
    authDomain: 'mnd-masterndelivery.firebaseapp.com',
    storageBucket: 'mnd-masterndelivery.firebasestorage.app',
    measurementId: 'G-FDGESSXFFM',
  );
}
