import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:mnd_rider/features/earnings/domain/rider_transaction.dart';
import 'package:mnd_rider/features/earnings/domain/rider_withdrawal.dart';
import 'package:mnd_rider/features/reports/domain/rider_report_data.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// Builds the rider's PDF report: earnings, cash, trip/delivery history and
/// the withdrawal/transaction log for one date range, on a single document.
abstract final class RiderReportPdfBuilder {
  static final DateFormat _rangeFmt = DateFormat('d MMM yyyy');
  static final DateFormat _rowDateFmt = DateFormat('d MMM, h:mm a');
  static final NumberFormat _lkrFmt = NumberFormat('#,##0');

  static final PdfColor _accent = PdfColor.fromHex('#0B6EFF');
  static final PdfColor _muted = PdfColor.fromHex('#5B6578');
  static final PdfColor _border = PdfColor.fromHex('#E2E8F0');
  static final PdfColor _headerFill = PdfColor.fromHex('#F3F5F8');
  static final PdfColor _zebraFill = PdfColor.fromHex('#FAFBFC');
  static final PdfColor _totalFill = PdfColor.fromHex('#EAF1FF');
  static final PdfColor _creditGreen = PdfColor.fromHex('#16A34A');
  static final PdfColor _debitRed = PdfColor.fromHex('#DC2626');

  static String _lkr(num value) => 'Rs. ${_lkrFmt.format(value.round())}';

  static Future<Uint8List> build({
    required RiderReportData data,
    required String riderName,
    required String riderPhone,
    required String vehicleNumber,
  }) async {
    final pw.Document doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(28, 32, 28, 28),
        header: (pw.Context context) => _header(
          context,
          data: data,
          riderName: riderName,
          riderPhone: riderPhone,
          vehicleNumber: vehicleNumber,
        ),
        footer: (pw.Context context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: <pw.Widget>[
            pw.Divider(color: _border, thickness: 0.75),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: <pw.Widget>[
                pw.Text(
                  'Generated by the MND Rider app — not a tax invoice.',
                  style: pw.TextStyle(fontSize: 7, color: _muted),
                ),
                pw.Text(
                  'Page ${context.pageNumber} of ${context.pagesCount}',
                  style: pw.TextStyle(fontSize: 7, color: _muted),
                ),
              ],
            ),
          ],
        ),
        build: (pw.Context context) => <pw.Widget>[
          pw.SizedBox(height: 12),
          _summarySection(data),
          pw.SizedBox(height: 16),
          _historySection(data),
          pw.SizedBox(height: 16),
          _cashSection(data),
          pw.SizedBox(height: 16),
          _transactionsSection(data),
        ],
      ),
    );

    return doc.save();
  }

  static pw.Widget _header(
    pw.Context context, {
    required RiderReportData data,
    required String riderName,
    required String riderPhone,
    required String vehicleNumber,
  }) {
    if (context.pageNumber > 1) {
      return pw.Column(
        children: <pw.Widget>[
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: <pw.Widget>[
              pw.Text(
                'MND Rider — activity report',
                style: pw.TextStyle(fontSize: 9, color: _muted),
              ),
              pw.Text(
                '${_rangeFmt.format(data.start)} — ${_rangeFmt.format(data.end)}',
                style: pw.TextStyle(fontSize: 9, color: _muted),
              ),
            ],
          ),
          pw.SizedBox(height: 6),
          pw.Divider(color: _border, thickness: 0.75),
        ],
      );
    }
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: <pw.Widget>[
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: <pw.Widget>[
                pw.Text(
                  'MND Rider',
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                    color: _accent,
                  ),
                ),
                pw.Text(
                  'Rider activity report',
                  style: pw.TextStyle(fontSize: 11, color: _muted),
                ),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: <pw.Widget>[
                pw.Text(
                  '${_rangeFmt.format(data.start)} — ${_rangeFmt.format(data.end)}',
                  style: pw.TextStyle(
                    fontSize: 11,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.Text(
                  'Generated ${_rowDateFmt.format(DateTime.now())}',
                  style: pw.TextStyle(fontSize: 8, color: _muted),
                ),
              ],
            ),
          ],
        ),
        pw.SizedBox(height: 10),
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 8),
          decoration: pw.BoxDecoration(
            color: _headerFill,
            borderRadius: pw.BorderRadius.circular(6),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: <pw.Widget>[
              pw.Text(
                riderName.isEmpty ? 'Rider' : riderName,
                style: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 10,
                ),
              ),
              if (riderPhone.isNotEmpty)
                pw.Text(riderPhone, style: const pw.TextStyle(fontSize: 10)),
              if (vehicleNumber.isNotEmpty)
                pw.Text(
                  vehicleNumber,
                  style: const pw.TextStyle(fontSize: 10),
                ),
            ],
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Divider(color: _border, thickness: 1),
      ],
    );
  }

  static pw.Widget _sectionTitle(String title, {String? trailing}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: <pw.Widget>[
          pw.Text(
            title,
            style: pw.TextStyle(
              fontSize: 13,
              fontWeight: pw.FontWeight.bold,
              color: _accent,
            ),
          ),
          if (trailing != null)
            pw.Text(
              trailing,
              style: pw.TextStyle(fontSize: 9, color: _muted),
            ),
        ],
      ),
    );
  }

  static pw.Widget _emptyNote(String message) => pw.Text(
        message,
        style: pw.TextStyle(fontSize: 9, color: _muted),
      );

  static pw.Widget _table({
    required List<String> headers,
    required List<List<String>> rows,
    Map<int, pw.TableColumnWidth>? columnWidths,
    Set<int> rightAlignColumns = const <int>{},
    pw.OnCellTextStyle? textStyleBuilder,
    int? boldLastRow,
  }) {
    final Map<int, pw.AlignmentGeometry> alignments =
        <int, pw.AlignmentGeometry>{
      for (final int col in rightAlignColumns) col: pw.Alignment.centerRight,
    };
    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: rows,
      headerStyle: pw.TextStyle(
        fontSize: 8,
        fontWeight: pw.FontWeight.bold,
        color: _accent,
      ),
      cellStyle: const pw.TextStyle(fontSize: 8),
      headerDecoration: pw.BoxDecoration(color: _headerFill),
      oddRowDecoration: pw.BoxDecoration(color: _zebraFill),
      border: pw.TableBorder.all(color: _border, width: 0.5),
      cellPadding: const pw.EdgeInsets.symmetric(horizontal: 5, vertical: 5),
      cellAlignments: alignments,
      headerAlignments: alignments,
      columnWidths: columnWidths,
      // `rowNum` counts the header row too (headerCount defaults to 1, and
      // we always pass `headers`), so a data row at 0-based index N in
      // [rows] arrives here as rowNum == N + 1.
      cellDecoration: boldLastRow == null
          ? null
          : (int index, dynamic cell, int rowNum) {
              return rowNum - 1 == boldLastRow
                  ? pw.BoxDecoration(color: _totalFill)
                  : const pw.BoxDecoration();
            },
      textStyleBuilder: (int index, dynamic cell, int rowNum) {
        if (boldLastRow != null && rowNum - 1 == boldLastRow) {
          return pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold);
        }
        return textStyleBuilder?.call(index, cell, rowNum);
      },
    );
  }

  static pw.Widget _summarySection(RiderReportData data) {
    pw.Widget stat(String label, String value, {PdfColor? accent}) {
      return pw.Expanded(
        child: pw.Container(
          padding: const pw.EdgeInsets.all(10),
          margin: const pw.EdgeInsets.only(right: 6),
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: _border),
            borderRadius: pw.BorderRadius.circular(6),
          ),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: <pw.Widget>[
              pw.Text(label, style: pw.TextStyle(fontSize: 8, color: _muted)),
              pw.SizedBox(height: 3),
              pw.Text(
                value,
                style: pw.TextStyle(
                  fontSize: 12,
                  fontWeight: pw.FontWeight.bold,
                  color: accent,
                ),
              ),
            ],
          ),
        ),
      );
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        _sectionTitle('Earnings & cash summary'),
        pw.Row(
          children: <pw.Widget>[
            stat(
              'Total earnings',
              _lkr(data.totalEarningsLkr),
              accent: _accent,
            ),
            stat('Total jobs', '${data.totalJobCount}'),
            stat('Deliveries', '${data.deliveryCount}'),
            stat('Rides', '${data.tripCount}'),
          ],
        ),
        pw.SizedBox(height: 6),
        pw.Row(
          children: <pw.Widget>[
            stat('Cash collected', _lkr(data.cashCollectedLkr)),
            stat('Owed to admin', _lkr(data.cashOwedLkr), accent: _debitRed),
            stat(
              'Kept from cash',
              _lkr(data.keptCashEarningLkr),
              accent: _creditGreen,
            ),
            stat('Withdrawn', _lkr(data.withdrawnLkr)),
          ],
        ),
      ],
    );
  }

  static pw.Widget _historySection(RiderReportData data) {
    final List<RiderReportHistoryEntry> entries = data.historyEntries;
    final List<List<String>> rows = entries
        .map(
          (RiderReportHistoryEntry e) => <String>[
            e.at != null ? _rowDateFmt.format(e.at!) : '—',
            e.isRide ? 'Ride' : 'Delivery',
            e.reference,
            e.title,
            _lkr(e.amountLkr),
          ],
        )
        .toList(growable: false);
    if (rows.isNotEmpty) {
      rows.add(<String>[
        '',
        '',
        '',
        'Total (${entries.length})',
        _lkr(
          entries.fold<double>(
            0.0,
            (double s, RiderReportHistoryEntry e) => s + e.amountLkr,
          ),
        ),
      ]);
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        _sectionTitle(
          'Trip & delivery history',
          trailing: entries.isEmpty ? null : '${entries.length} jobs',
        ),
        if (rows.isEmpty)
          _emptyNote('No completed trips or deliveries in this period.')
        else
          _table(
            headers: <String>[
              'Date',
              'Type',
              'Reference',
              'Route / store',
              'Amount',
            ],
            rows: rows,
            rightAlignColumns: const <int>{4},
            boldLastRow: rows.length - 1,
            columnWidths: const <int, pw.TableColumnWidth>{
              0: pw.FlexColumnWidth(1.6),
              1: pw.FlexColumnWidth(1),
              2: pw.FlexColumnWidth(1.4),
              3: pw.FlexColumnWidth(2.2),
              4: pw.FlexColumnWidth(1.2),
            },
          ),
      ],
    );
  }

  static pw.Widget _cashSection(RiderReportData data) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        _sectionTitle('Cash owed breakdown'),
        if (data.cashEntries.isEmpty)
          _emptyNote('No cash was collected in this period.')
        else
          _table(
            headers: <String>['Component', 'Amount'],
            rows: <List<String>>[
              <String>['Shop product cost', _lkr(data.productCashLkr)],
              <String>['Service charge', _lkr(data.serviceChargeLkr)],
              <String>['Ride commission', _lkr(data.rideCommissionLkr)],
              <String>['Total owed to admin', _lkr(data.cashOwedLkr)],
              <String>['Settled (confirmed)', _lkr(data.settledCashLkr)],
            ],
            rightAlignColumns: const <int>{1},
            boldLastRow: 3,
          ),
      ],
    );
  }

  static pw.Widget _transactionsSection(RiderReportData data) {
    final List<List<String>> withdrawalRows = data.withdrawals
        .map(
          (RiderWithdrawal w) => <String>[
            w.createdAt != null
                ? _rowDateFmt.format(w.createdAt!.toLocal())
                : '—',
            _lkr(w.amountLkr),
            w.payoutMethod,
            _withdrawalStatusLabel(w.status),
          ],
        )
        .toList(growable: false);

    final List<List<String>> transactionRows = data.transactions
        .map(
          (RiderTransaction t) => <String>[
            t.createdAt != null
                ? _rowDateFmt.format(t.createdAt!.toLocal())
                : '—',
            t.title,
            '${t.isCredit ? '+' : ''}${_lkr(t.amountLkr)}',
          ],
        )
        .toList(growable: false);

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        _sectionTitle('Withdrawals'),
        if (withdrawalRows.isEmpty)
          _emptyNote('No withdrawal requests in this period.')
        else
          _table(
            headers: <String>['Date', 'Amount', 'Method', 'Status'],
            rows: withdrawalRows,
            rightAlignColumns: const <int>{1},
          ),
        pw.SizedBox(height: 14),
        _sectionTitle('Wallet transaction log'),
        if (transactionRows.isEmpty)
          _emptyNote('No wallet transactions in this period.')
        else
          _table(
            headers: <String>['Date', 'Description', 'Amount'],
            rows: transactionRows,
            rightAlignColumns: const <int>{2},
            textStyleBuilder: (int index, dynamic cell, int rowNum) {
              if (index != 2) {
                return null;
              }
              final String text = cell.toString();
              return pw.TextStyle(
                fontSize: 8,
                color: text.startsWith('+') ? _creditGreen : _debitRed,
                fontWeight: pw.FontWeight.bold,
              );
            },
          ),
      ],
    );
  }

  static String _withdrawalStatusLabel(RiderWithdrawalStatus status) {
    switch (status) {
      case RiderWithdrawalStatus.pending:
        return 'Pending';
      case RiderWithdrawalStatus.approved:
        return 'Approved';
      case RiderWithdrawalStatus.rejected:
        return 'Rejected';
      case RiderWithdrawalStatus.paid:
        return 'Paid';
    }
  }
}
